### ISSUE TITLE
Fix module check

### ISSUE THREAD

**Issue by marcellussiegburg** [fmidue/haskell-template-task#1]
Module parsing seems to fail if the module name does not match. Leading to a misleading error message:
![image](https://user-images.githubusercontent.com/531939/110780943-918a4d80-8265-11eb-9432-d0162dc89242.png)

(Either) It should happen in the `ParseError` case here (or the module is written to the "wrong" location - but be careful to not expose internal modules if changing the latter):
https://github.com/fmidue/haskell-template-task/blob/894c288b2d15bd6e7e9574c740e6f0769699f7a1/src/Haskell/Template/Task.hs#L571-L578

**Comment by jvoigtlaender** [comment]
Is this still relevant?

**Comment by marcellussiegburg** [comment]
I think this is not relevant any more. There have been changes on allowing different module names. Usually such changes are rejected because of a template mismatch (which is expected). If the issue reoccurs, this ticket might be reopened (or a new one created).
