### ISSUE TITLE
Allow for flexible module name during check

### ISSUE THREAD

**Issue by marcellussiegburg** [fmidue/haskell-template-task#2]
Probably fix the hardcoded reading of the solution file, e.g. by introducing an additional argument:

https://github.com/fmidue/haskell-template-task/blob/894c288b2d15bd6e7e9574c740e6f0769699f7a1/embedded/src/TestHarness.hs#L116

Could be related to the behaviour of #1?

**Comment by jvoigtlaender** [comment]
Is this still relevant?

**Comment by marcellussiegburg** [comment]
Yes, the issue has not been addressed yet. But think, it has no high priority as it can be circumvented by naming the module `Solution` if required.

**Comment by jvoigtlaender** [comment]
Just took a look, and I guess it has actually been addressed, though in an extremely hacky way. :smile:

https://github.com/fmidue/haskell-template-task/blob/bf621d5a91c487ad23c53cfa588a0277e99c0381/src/Haskell/Template/Task.hs#L374

**Comment by jvoigtlaender** [comment]
Looking up the commit that introduced this ... commit message is "fix module name in TestHarness (very hacky)" :smile:
